[project]
name = "projeto-yoneda-z3"
version = "0.1.0"
description = ""
authors = [
    {name = "JoseAugustoMAJ(jamaj)",email = "jamaj@jamaj.com.br"}
]
requires-python = ">=3.11"
dependencies = [
    "z3-solver (>=4.16.0.0,<5.0.0.0)",
    "requests (>=2.33.0,<3.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
